private _return = ["BCE_TaskBuilding_SendData", []] call CBA_fnc_localEvent;
_return
//-H-60
/*[
	"TESTMESSAGE",//TITLE
	"IMAGINARYJTAC",//SENDER
	"ALL",//RECIPIENTS
	1,//MSGTYPE
	[
		"TYPE2,USEROCKETS",
		"500MNORTHOFAGIAMARINA",
		"AGIAMARINA-123123/12m",
		"2xBTR-80APARKEDONROAD",//description
		"",
		"ATTACKWESTTOEAST",//restrictions
		"",
		"",
		"",
		""
	],//MSGTEXT
	[],//MSGDATA
	[
		[
			"12:00",
			"System",
			"SENT"
		]
	]//REPLIES
] */
